apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: rqlite
    name: rqlite
  spec:
    ports:
    - name: http
      port: 4001
      protocol: TCP
      targetPort: 4001
    - name: rqlitetcp
      port: 4002
      protocol: TCP
      targetPort: 4002
    clusterIP: None
    selector:
      app: rqlite
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    labels:
      app: rqlite
    name: rqlite
  spec:
    podManagementPolicy: OrderedReady
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: rqlite
    serviceName: rqlite
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: rqlite
      spec:
        containers:
        - image: theog75/rqlite
          env:
          imagePullPolicy: Always
          name: rqlite
          ports:
          - containerPort: 4001
            protocol: TCP
          - containerPort: 4002
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
